build_cloud: VLADDEN
image: Windows
version: '{branch}-{build}'

dotnet_csproj:
  patch: true
  file: 'TGBot\TGBot.csproj'
  version: '0.0.{build}'

before_build:
  - cmd: dotnet --info
  - cmd: nuget restore -verbosity quiet
